### ISSUE TITLE
僕は長濱ねるちゃん！

### ISSUE THREAD

**Issue by Pittan** [Pittan/PerfumeHub-web#31]
個別握手会の券、長濱ねるちゃん取れなかったから佐藤詩織さんに傾きつつあります 😢

**Comment by Pittan** [comment]
![imkr8023](https://cloud.githubusercontent.com/assets/6269639/24366673/c52d815e-1354-11e7-82a8-d8e2b7d5ff43.jpg)

**Comment by Pittan** [comment]
これはLGTMですわ…

**Comment by fumiya-kume** [comment]
http://cdn.keyakizaka46.com/files/14/diary/k46/member/moblog/201703/mobTjDXQM.jpg
わかる

**Comment by Pittan** [comment]
LINEスタンプ出たのでみんな買おうね 📱 💬
